server:
  port: 8001

# mybaits配置
#mybatis:
#  type-aliases-package: com.xiaofeng.blogs.*.entity    # 所有Entity别名类所在包

# spring配置
spring:
  application:
    name: example-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf-8&useSSL=false              # 数据库名称
    username: root
    password: root

# eureka配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka             #指定去哪个微服务注册
      #集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: example-provider-8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 #设置服务失效时间（默认90秒）