server:
  port: 7003

spring:
  application:
    name: eureka7003.com

eureka:
  instance:
    hostname: eureka7003.com #eureka服务端的实例名称
    instance-id: example-eureka-7003
    prefer-ip-address: true
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。 单机一般是false，高可用一般是true
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务  单机一般是false，高可用一般是true
    service-url:
      #单机版
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 指向另外两个eureka



