server:
  port: 80

spring:
  application:
    name: example-consumer-80

eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: example-consumer-80
    prefer-ip-address: true

logging:
  level:
    com:
      xiaofeng:
        example: debug

---
server:
  port: 9527
spring:
  profiles: prod

---
server:
  port: 80
spring:
  profiles: dev